#!/usr/bin/env python3
"""
Generate GitHub issue creation commands.

This script reads the issue templates generated by analyze_tsv_coverage.py
and creates shell commands or instructions for creating GitHub issues.

Usage: python scripts/create_coverage_issues.py [--output-file FILE]
"""

import argparse
import json
from pathlib import Path


def generate_issue_commands(reports_dir: Path, output_file: Path = None) -> None:
    """
    Generate commands or instructions for creating GitHub issues.
    
    Args:
        reports_dir: Directory containing coverage reports
        output_file: Optional output file for commands
    """
    issues_dir = reports_dir / "issues"
    json_file = reports_dir / "coverage_data.json"
    
    if not issues_dir.exists():
        print(f"Error: Issues directory not found: {issues_dir}")
        return
    
    if not json_file.exists():
        print(f"Error: Coverage data JSON not found: {json_file}")
        return
    
    # Read coverage data
    with open(json_file, 'r') as f:
        coverage_data = json.load(f)
    
    # Generate instructions
    lines = []
    lines.append("# GitHub Issue Creation Instructions\n")
    lines.append("## Coverage Pattern Issues\n")
    lines.append(f"Based on the analysis, {len(coverage_data)} unique header coverage patterns were found.\n")
    lines.append("Below are the details for creating an issue for each pattern.\n\n")
    
    lines.append("---\n\n")
    
    for idx, pattern in enumerate(coverage_data, 1):
        issue_file = issues_dir / f"pattern_{idx}_issue.md"
        
        if not issue_file.exists():
            continue
        
        # Read the issue content
        with open(issue_file, 'r') as f:
            content = f.read()
        
        # Extract title and labels
        title = f"TSV Header Coverage Pattern {idx} - {pattern['file_count']} files with {pattern['statistics']['coverage_percent']:.1f}% coverage"
        
        labels = ["data-quality", "headers"]
        if pattern['statistics']['unexpected']:
            labels.append("unexpected-headers")
        if pattern['statistics']['coverage_percent'] < 50:
            labels.append("low-coverage")
        
        # Generate issue creation instructions
        lines.append(f"## Issue {idx}: Pattern {idx}\n\n")
        lines.append(f"**Title:** `{title}`\n\n")
        lines.append(f"**Labels:** {', '.join(labels)}\n\n")
        lines.append(f"**Statistics:**\n")
        lines.append(f"- Files: {pattern['file_count']}\n")
        lines.append(f"- Coverage: {pattern['statistics']['coverage_percent']:.1f}%\n")
        lines.append(f"- Missing headers: {pattern['statistics']['missing']}\n")
        
        if pattern['statistics']['unexpected']:
            lines.append(f"- **Unexpected headers:** {pattern['statistics']['unexpected']} ⚠️\n")
        
        lines.append(f"\n**Body:** See `{issue_file.relative_to(reports_dir.parent.parent)}`\n\n")
        
        lines.append("### To create this issue manually:\n\n")
        lines.append("1. Go to https://github.com/bge-barcoding/bge-skimming-analytics/issues/new\n")
        lines.append(f"2. Title: `{title}`\n")
        lines.append(f"3. Labels: {', '.join(labels)}\n")
        lines.append(f"4. Body: Copy content from `{issue_file.relative_to(reports_dir.parent.parent)}`\n\n")
        
        lines.append("---\n\n")
    
    # Write output
    output_content = ''.join(lines)
    
    if output_file:
        with open(output_file, 'w') as f:
            f.write(output_content)
        print(f"Issue creation instructions saved to: {output_file}")
    else:
        print(output_content)


def main():
    """Main function."""
    parser = argparse.ArgumentParser(
        description='Generate GitHub issue creation instructions'
    )
    parser.add_argument(
        '--reports-dir',
        type=Path,
        default=Path(__file__).parent.parent / 'reports' / 'coverage',
        help='Directory containing coverage reports (default: reports/coverage)'
    )
    parser.add_argument(
        '--output-file',
        type=Path,
        help='Output file for instructions (default: print to stdout)'
    )
    args = parser.parse_args()
    
    generate_issue_commands(args.reports_dir, args.output_file)


if __name__ == '__main__':
    main()
